<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ArticleRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        if (request('id', '')) {
            return [
                'category_id' => 'required',
                'title' => 'required|string|max:100|min:5|unique:articles,title,' . $this->id,
                'content'  => 'required|string|min:10'
            ];
        } else {
            return [
                'category_id' => 'required',
                'title' => 'required|string|max:100|unique:articles,title',
                'content'  => 'required|string|min:10'
            ];
        }
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
